### ISSUE TITLE
🪲 Bug Report - Outbound Rule fails to create if backend pool contains more than 6 IPs

### ISSUE THREAD

**Issue by hevcy** [Azure/AzLoadBalancerMigration#114]
## Describe the bug

When running AzurePublicLBUpgrade.ps1 against a load balancer with a single backend pool, with, for example, 10 endpoints, you recieve an error: 

`Outboundrule exceeds total number of available ports per backend instance of 6392 based upon desired pool size. Reduce allocated ports or increase number of IP addresses for outbound rule.` 

This is because in the script the outbound rule is hard-coded to use 10000 ports per instance. This should probably be calculated based upon how many ip configurations exist within a backend pool.

## To Reproduce

1. Create Basic LB with a single backend pool with >=7 Ip configurations
2. Run Script

## Expected behavior

Outbound rule is correctly created

## Screenshots 📷

n/a

## Additional context - please include:

Version 7.0

**Comment by mbrat2005** [comment]
This is a known limitation of this legacy script. Use https://www.powershellgallery.com/packages/AzureBasicLoadBalancerUpgrade instead
