### ISSUE TITLE
Uniqueness of VMSS entries incorrect if case differs between resource IDs

### ISSUE THREAD

**Issue by bjh1977** [Azure/AzLoadBalancerMigration#19]
I have a scaleset which originally had 5 instances. At a later date, 5 more were added.  For some reason, the "old" instances show the resource group name capitalised, whereas the new ones do not.  This is causing error:

`##[error][Error]:[Test-SupportedMigrationScenario] Basic Load Balancer has more than one VMSS in the backend pool, exiting`

This issue probably relates to the inconsistent behaviour referenced in https://github.com/PowerShell/PowerShell/issues/12059.

**Comment by mbrat2005** [comment]
@bjh1977 Thanks for raising this issue! I've updated the module to always lowercase the VMSS resource ID. Please give it a try!
